name: 'HTTP Client Custom Action'
description: 'Custom action for doing the http operations'
inputs:
  LeapDNABaseUrl:
    description: 'The LeapDNABaseUrl endpoint to send the HTTP request to'
    required: true
  Output:
    description: 'The Output to include in the request body'
    required: false
  ClientId:
    description: 'The ClientId for authenticaton'
    required: false
  ClientSecret:
    description: 'The ClientSecret for authentication'
    required: false
  TenantId:
    description: 'The TenantId for authentication'
    required: false
  CertificateBase64:
    description: 'CertificateBase64 for authentication'
    required: false
outputs:
  response:
    description: 'The response body received from the POST request'
  headers:
    description: 'The headers received in the response'
runs:
  using: 'node16'
  main: 'dist/index.js'
