on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:
    inputs:     
      Input1:
        description: 'Input1'
        required: true
        default: 'Input1'
      Input2:
        description: 'Input2'
        required: false
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    outputs:
      outputTime: ${{ steps.hello.outputs.time }}
    steps:
      - name: Hello world action step
        id: hello
        uses: pratikkamle/hello-world-javascript-action@v1.1.2
        with:
          who-to-greet: 'Pratik Kamle'
          url: 'https://enp7gmdcs56pb.x.pipedream.net/'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"Current Job status": "Success"}'
      # Use the output from the `hello` step
      - name: Get the output time Custom action
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Show Response Custom action
        run: |
          echo ${{ steps.hello.outputs.response }}
          echo ${{ steps.hello.outputs.headers }}
  http_client_job:
    if: ${{ always() }}
    needs: hello_world_job
    runs-on: ubuntu-latest
    name: A job to post http request
    steps:
      - name: HTTP Client Action
        id: http-client-action
        uses: pratikkamle/http-client-custom-action@v2.6.0
        with:
          LeapDNABaseUrl: 'https://enp7gmdcs56pb.x.pipedream.net/'
          ClientSecret: 'clientSecretFromInput'
          TenantId: 'TenantIdFromInput'
          CertificateBase64: 'CertificateBase64FromInput'
          Output: '{"HTTP Custom action status v2.6.0": "Success"}'
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      # Use the output from the `http-client-action` step
#       - name: Get the response output
#         run: |
#           echo "The time HTTP request was made ${{ steps.hello.outputs.time }}"
#           echo ${{ steps.http-client-action.outputs.response }}
#           echo ${{ steps.http-client-action.outputs.headers }}
