on: [push]

jobs:
  http_client_job:
    runs-on: ubuntu-latest
    name: A job to post http request
    steps:
      - name: HTTP Client Action
        id: http-client-action
        uses: pratikkamle/http-client-custom-action@v2.0.1
        with:
          LeapDNABaseUrl: 'https://enp7gmdcs56pb.x.pipedream.net/'
          ClientSecret: 'clientSecretFromInput'
          TenantId: 'TenantIdFromInput'
          CertificateBase64: 'CertificateBase64FromInput'
          Output: '{"HTTP Custom action status v2.0.1": "Success"}'
      # Use the output from the `http-client-action` step
      - name: Get the response output
        run: |
          echo "The time HTTP request was made ${{ steps.hello.outputs.time }}"
          echo ${{ steps.http-client-action.outputs.response }}
          echo ${{ steps.http-client-action.outputs.headers }}
